-- MySQL Script generated by MySQL Workbench
-- Mon May 23 20:32:08 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Tempo_Buono_New
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Tempo_Buono_New` ;

-- -----------------------------------------------------
-- Schema Tempo_Buono_New
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Tempo_Buono_New` DEFAULT CHARACTER SET utf8 ;
USE `Tempo_Buono_New` ;

-- -----------------------------------------------------
-- Table `Tempo_Buono_New`.`usersCategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tempo_Buono_New`.`usersCategory` ;

CREATE TABLE IF NOT EXISTS `Tempo_Buono_New`.`usersCategory` (
  `idusersCategory` INT NOT NULL AUTO_INCREMENT,
  `usersCategoryNombre` TEXT(45) NOT NULL,
  `usersCategoryDesc` TEXT(45) NOT NULL,
  PRIMARY KEY (`idusersCategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tempo_Buono_New`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tempo_Buono_New`.`users` ;

CREATE TABLE IF NOT EXISTS `Tempo_Buono_New`.`users` (
  `idUsers` INT NOT NULL AUTO_INCREMENT,
  `UsersNombre` TEXT(45) NOT NULL,
  `UsersEmail` VARCHAR(45) NOT NULL,
  `UsersPasswd` VARCHAR(255) NOT NULL,
  `usersCategory_idusersCategory` INT NOT NULL,
  PRIMARY KEY (`idUsers`),
  CONSTRAINT `fk_users_usersCategory1`
    FOREIGN KEY (`usersCategory_idusersCategory`)
    REFERENCES `Tempo_Buono_New`.`usersCategory` (`idusersCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_users_usersCategory1_idx` ON `Tempo_Buono_New`.`users` (`usersCategory_idusersCategory` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Tempo_Buono_New`.`productsCategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tempo_Buono_New`.`productsCategory` ;

CREATE TABLE IF NOT EXISTS `Tempo_Buono_New`.`productsCategory` (
  `idproductsCategory` INT NOT NULL AUTO_INCREMENT,
  `productsCategorNombre` TEXT(45) NOT NULL,
  `productsCategoryDesc` TEXT(45) NOT NULL,
  PRIMARY KEY (`idproductsCategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tempo_Buono_New`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tempo_Buono_New`.`products` ;

CREATE TABLE IF NOT EXISTS `Tempo_Buono_New`.`products` (
  `idProd` INT NOT NULL AUTO_INCREMENT,
  `ProductsName` TEXT(45) NOT NULL,
  `ProductsDescription` VARCHAR(45) NOT NULL,
  `ProductsPrice` FLOAT(255) NOT NULL,
  `productsCategory_idproductsCategory` INT NOT NULL,
  PRIMARY KEY (`idProd`),
  CONSTRAINT `fk_products_productsCategory`
    FOREIGN KEY (`productsCategory_idproductsCategory`)
    REFERENCES `Tempo_Buono_New`.`productsCategory` (`idproductsCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_products_productsCategory_idx` ON `Tempo_Buono_New`.`products` (`productsCategory_idproductsCategory` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Tempo_Buono_New`.`productsImages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tempo_Buono_New`.`productsImages` ;

CREATE TABLE IF NOT EXISTS `Tempo_Buono_New`.`productsImages` (
  `idproductsImages` INT NOT NULL AUTO_INCREMENT,
  `productsImagesNombre` VARCHAR(45) NOT NULL,
  `productsImagesDesc` VARCHAR(45) NOT NULL,
  `products_idProd` INT NOT NULL,
  PRIMARY KEY (`idproductsImages`),
  CONSTRAINT `fk_productsImages_products1`
    FOREIGN KEY (`products_idProd`)
    REFERENCES `Tempo_Buono_New`.`products` (`idProd`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_productsImages_products1_idx` ON `Tempo_Buono_New`.`productsImages` (`products_idProd` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Tempo_Buono_New`.`productsCombo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tempo_Buono_New`.`productsCombo` ;

CREATE TABLE IF NOT EXISTS `Tempo_Buono_New`.`productsCombo` (
  `idproductsCombo` INT NOT NULL AUTO_INCREMENT,
  `productsComprecio` FLOAT(45) NOT NULL,
  PRIMARY KEY (`idproductsCombo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tempo_Buono_New`.`products_has_productsCombo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tempo_Buono_New`.`products_has_productsCombo` ;

CREATE TABLE IF NOT EXISTS `Tempo_Buono_New`.`products_has_productsCombo` (
  `products_idProd` INT NOT NULL,
  `productsCombo_idproductsCombo` INT NOT NULL,
  PRIMARY KEY (`products_idProd`, `productsCombo_idproductsCombo`),
  CONSTRAINT `fk_products_has_productsCombo_products1`
    FOREIGN KEY (`products_idProd`)
    REFERENCES `Tempo_Buono_New`.`products` (`idProd`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_has_productsCombo_productsCombo1`
    FOREIGN KEY (`productsCombo_idproductsCombo`)
    REFERENCES `Tempo_Buono_New`.`productsCombo` (`idproductsCombo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_products_has_productsCombo_productsCombo1_idx` ON `Tempo_Buono_New`.`products_has_productsCombo` (`productsCombo_idproductsCombo` ASC) VISIBLE;

CREATE INDEX `fk_products_has_productsCombo_products1_idx` ON `Tempo_Buono_New`.`products_has_productsCombo` (`products_idProd` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Tempo_Buono_New`.`Cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tempo_Buono_New`.`Cart` ;

CREATE TABLE IF NOT EXISTS `Tempo_Buono_New`.`Cart` (
  `idCart` INT NOT NULL AUTO_INCREMENT,
  `CartQantity` INT NOT NULL,
  `CartTotal` FLOAT NOT NULL,
  `users_idUsers` INT NOT NULL,
  `CartDate` DATE NOT NULL,
  PRIMARY KEY (`idCart`),
  CONSTRAINT `fk_Cart_users1`
    FOREIGN KEY (`users_idUsers`)
    REFERENCES `Tempo_Buono_New`.`users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Cart_users1_idx` ON `Tempo_Buono_New`.`Cart` (`users_idUsers` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Tempo_Buono_New`.`Cart_has_products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tempo_Buono_New`.`Cart_has_products` ;

CREATE TABLE IF NOT EXISTS `Tempo_Buono_New`.`Cart_has_products` (
  `Cart_idCart` INT NOT NULL,
  `products_idProd` INT NOT NULL,
  `CartProdQtty` INT NOT NULL,
  `CartProdPrice` FLOAT NOT NULL,
  PRIMARY KEY (`Cart_idCart`, `products_idProd`),
  CONSTRAINT `fk_Cart_has_products_Cart1`
    FOREIGN KEY (`Cart_idCart`)
    REFERENCES `Tempo_Buono_New`.`Cart` (`idCart`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cart_has_products_products1`
    FOREIGN KEY (`products_idProd`)
    REFERENCES `Tempo_Buono_New`.`products` (`idProd`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Cart_has_products_products1_idx` ON `Tempo_Buono_New`.`Cart_has_products` (`products_idProd` ASC) VISIBLE;

CREATE INDEX `fk_Cart_has_products_Cart1_idx` ON `Tempo_Buono_New`.`Cart_has_products` (`Cart_idCart` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `Tempo_Buono_New`.`usersCategory`
-- -----------------------------------------------------
START TRANSACTION;
USE `Tempo_Buono_New`;
INSERT INTO `Tempo_Buono_New`.`usersCategory` (`idusersCategory`, `usersCategoryNombre`, `usersCategoryDesc`) VALUES (1, 'Usuario', 'Usuario Normal');
INSERT INTO `Tempo_Buono_New`.`usersCategory` (`idusersCategory`, `usersCategoryNombre`, `usersCategoryDesc`) VALUES (2, 'Admin', 'Usuario Administrador');

COMMIT;


-- -----------------------------------------------------
-- Data for table `Tempo_Buono_New`.`users`
-- -----------------------------------------------------
START TRANSACTION;
USE `Tempo_Buono_New`;
INSERT INTO `Tempo_Buono_New`.`users` (`idUsers`, `UsersNombre`, `UsersEmail`, `UsersPasswd`, `usersCategory_idusersCategory`) VALUES (1, 'Daniel Devitta', 'dani@test.com', 'dani', 2);
INSERT INTO `Tempo_Buono_New`.`users` (`idUsers`, `UsersNombre`, `UsersEmail`, `UsersPasswd`, `usersCategory_idusersCategory`) VALUES (2, 'Fede Diaz', 'fede@test.com', 'fede', 2);
INSERT INTO `Tempo_Buono_New`.`users` (`idUsers`, `UsersNombre`, `UsersEmail`, `UsersPasswd`, `usersCategory_idusersCategory`) VALUES (3, 'Maria Gaitan', 'maria@test.com', 'maria', 2);
INSERT INTO `Tempo_Buono_New`.`users` (`idUsers`, `UsersNombre`, `UsersEmail`, `UsersPasswd`, `usersCategory_idusersCategory`) VALUES (4, 'Gaston Ortega', 'gaston@test.com', 'gaston', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `Tempo_Buono_New`.`productsCategory`
-- -----------------------------------------------------
START TRANSACTION;
USE `Tempo_Buono_New`;
INSERT INTO `Tempo_Buono_New`.`productsCategory` (`idproductsCategory`, `productsCategorNombre`, `productsCategoryDesc`) VALUES (1, 'Alfajor', '0');
INSERT INTO `Tempo_Buono_New`.`productsCategory` (`idproductsCategory`, `productsCategorNombre`, `productsCategoryDesc`) VALUES (2, 'Cafe', '0');

COMMIT;

