-- MySQL Script generated by MySQL Workbench
-- Tue May 17 23:09:40 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Tempo_Bouono
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Tempo_Bouono` ;

-- -----------------------------------------------------
-- Schema Tempo_Bouono
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Tempo_Bouono` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `Tempo_Bouono` ;

-- -----------------------------------------------------
-- Table `Tempo_Bouono`.`UsersType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tempo_Bouono`.`UsersType` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Tempo_Bouono`.`UsersType` (
  `idUsersType` INT NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(6) NOT NULL DEFAULT 'Normal',
  PRIMARY KEY (`idUsersType`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Tempo_Bouono`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tempo_Bouono`.`Users` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Tempo_Bouono`.`Users` (
  `idUsers` INT NOT NULL AUTO_INCREMENT,
  `UsersName` VARCHAR(45) NOT NULL,
  `UsersSurname` VARCHAR(45) NOT NULL,
  `UsrsEmail` VARCHAR(45) NOT NULL,
  `UsersType_idUsersType` INT NOT NULL,
  `UsersTelephone` VARCHAR(45) NOT NULL,
  `UsersType_idUsersType1` INT NOT NULL,
  PRIMARY KEY (`idUsers`, `UsersType_idUsersType`, `UsersType_idUsersType1`),
  CONSTRAINT `fk_Users_UsersType1`
    FOREIGN KEY (`UsersType_idUsersType1`)
    REFERENCES `Tempo_Bouono`.`UsersType` (`idUsersType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idUsers_UNIQUE` ON `Tempo_Bouono`.`Users` (`idUsers` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Users_UsersType1_idx` ON `Tempo_Bouono`.`Users` (`UsersType_idUsersType1` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Tempo_Bouono`.`Pais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tempo_Bouono`.`Pais` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Tempo_Bouono`.`Pais` (
  `idPais` INT NOT NULL AUTO_INCREMENT,
  `PaisName` VARCHAR(45) NOT NULL,
  `PaisAbbr` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPais`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Tempo_Bouono`.`Localidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tempo_Bouono`.`Localidad` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Tempo_Bouono`.`Localidad` (
  `idLocalidad` INT NOT NULL AUTO_INCREMENT,
  `LocalidadNombre` VARCHAR(45) NOT NULL,
  `LocalidadCodigoPostal` INT NOT NULL,
  `Pais_idPais` INT NOT NULL,
  PRIMARY KEY (`idLocalidad`, `Pais_idPais`),
  CONSTRAINT `fk_Localidad_Pais1`
    FOREIGN KEY (`Pais_idPais`)
    REFERENCES `Tempo_Bouono`.`Pais` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Localidad_Pais1_idx` ON `Tempo_Bouono`.`Localidad` (`Pais_idPais` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Tempo_Bouono`.`Direcciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tempo_Bouono`.`Direcciones` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Tempo_Bouono`.`Direcciones` (
  `idDirecciones` INT NOT NULL AUTO_INCREMENT,
  `DireccionesCalle` VARCHAR(45) NOT NULL,
  `DireccionesNumero` INT NOT NULL,
  `Direccionescol` VARCHAR(45) NOT NULL,
  `Users_idUsers` INT NOT NULL,
  `Users_UsersType_idUsersType` INT NOT NULL,
  `Localidad_idLocalidad` INT NOT NULL,
  `Localidad_Pais_idPais` INT NOT NULL,
  PRIMARY KEY (`idDirecciones`, `Users_idUsers`, `Users_UsersType_idUsersType`, `Localidad_idLocalidad`, `Localidad_Pais_idPais`),
  CONSTRAINT `fk_Direcciones_Users1`
    FOREIGN KEY (`Users_idUsers` , `Users_UsersType_idUsersType`)
    REFERENCES `Tempo_Bouono`.`Users` (`idUsers` , `UsersType_idUsersType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Direcciones_Localidad1`
    FOREIGN KEY (`Localidad_idLocalidad` , `Localidad_Pais_idPais`)
    REFERENCES `Tempo_Bouono`.`Localidad` (`idLocalidad` , `Pais_idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Direcciones_Users1_idx` ON `Tempo_Bouono`.`Direcciones` (`Users_idUsers` ASC, `Users_UsersType_idUsersType` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Direcciones_Localidad1_idx` ON `Tempo_Bouono`.`Direcciones` (`Localidad_idLocalidad` ASC, `Localidad_Pais_idPais` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Tempo_Bouono`.`ProductDiscounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tempo_Bouono`.`ProductDiscounts` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Tempo_Bouono`.`ProductDiscounts` (
  `idProductDiscounts` INT NOT NULL AUTO_INCREMENT,
  `ProductDiscountName` VARCHAR(45) NOT NULL,
  `ProductDiscountsNumber` INT NOT NULL,
  PRIMARY KEY (`idProductDiscounts`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Tempo_Bouono`.`ProductType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tempo_Bouono`.`ProductType` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Tempo_Bouono`.`ProductType` (
  `idProductType` INT NOT NULL AUTO_INCREMENT,
  `ProductTypeName` VARCHAR(45) NULL,
  PRIMARY KEY (`idProductType`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Tempo_Bouono`.`Productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tempo_Bouono`.`Productos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Tempo_Bouono`.`Productos` (
  `idProductos` INT NOT NULL,
  `ProductName` VARCHAR(45) NULL,
  `ProductPrice` VARCHAR(45) NULL,
  `ProductDescription` VARCHAR(45) NULL,
  `ProductType_idProductType` INT NOT NULL,
  `ProductDiscounts_idProductDiscounts` INT NOT NULL,
  `ProductType_idProductType1` INT NOT NULL,
  PRIMARY KEY (`idProductos`, `ProductType_idProductType`, `ProductDiscounts_idProductDiscounts`, `ProductType_idProductType1`),
  CONSTRAINT `fk_Productos_ProductDiscounts1`
    FOREIGN KEY (`ProductDiscounts_idProductDiscounts`)
    REFERENCES `Tempo_Bouono`.`ProductDiscounts` (`idProductDiscounts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_ProductType1`
    FOREIGN KEY (`ProductType_idProductType1`)
    REFERENCES `Tempo_Bouono`.`ProductType` (`idProductType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Productos_ProductDiscounts1_idx` ON `Tempo_Bouono`.`Productos` (`ProductDiscounts_idProductDiscounts` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Productos_ProductType1_idx` ON `Tempo_Bouono`.`Productos` (`ProductType_idProductType1` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Tempo_Bouono`.`Orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tempo_Bouono`.`Orders` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Tempo_Bouono`.`Orders` (
  `idorders` INT NOT NULL AUTO_INCREMENT,
  `OrderDate` DATETIME NOT NULL,
  `OrderQuantity` VARCHAR(45) NOT NULL,
  `OrderUnitPrice` VARCHAR(45) NOT NULL,
  `Users_idUsers` INT NOT NULL,
  `Users_UsersType_idUsersType` INT NOT NULL,
  `Users_UsersType_idUsersType1` INT NOT NULL,
  PRIMARY KEY (`idorders`, `Users_idUsers`, `Users_UsersType_idUsersType`, `Users_UsersType_idUsersType1`),
  CONSTRAINT `fk_Orders_Users1`
    FOREIGN KEY (`Users_idUsers` , `Users_UsersType_idUsersType` , `Users_UsersType_idUsersType1`)
    REFERENCES `Tempo_Bouono`.`Users` (`idUsers` , `UsersType_idUsersType` , `UsersType_idUsersType1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Orders_Users1_idx` ON `Tempo_Bouono`.`Orders` (`Users_idUsers` ASC, `Users_UsersType_idUsersType` ASC, `Users_UsersType_idUsersType1` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Tempo_Bouono`.`OrdenItems`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tempo_Bouono`.`OrdenItems` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Tempo_Bouono`.`OrdenItems` (
  `idOrdenesItems` INT NOT NULL AUTO_INCREMENT,
  `Orders_idorders` INT NOT NULL,
  `Orders_Users_idUsers` INT NOT NULL,
  `Orders_Users_UsersType_idUsersType` INT NOT NULL,
  `Orders_Users_UsersType_idUsersType1` INT NOT NULL,
  `Productos_idProductos` INT NOT NULL,
  `Productos_ProductType_idProductType` INT NOT NULL,
  `Productos_ProductDiscounts_idProductDiscounts` INT NOT NULL,
  `Productos_ProductType_idProductType1` INT NOT NULL,
  PRIMARY KEY (`idOrdenesItems`, `Orders_idorders`, `Orders_Users_idUsers`, `Orders_Users_UsersType_idUsersType`, `Orders_Users_UsersType_idUsersType1`, `Productos_idProductos`, `Productos_ProductType_idProductType`, `Productos_ProductDiscounts_idProductDiscounts`, `Productos_ProductType_idProductType1`),
  CONSTRAINT `fk_DetalleOrdenes_Orders1`
    FOREIGN KEY (`Orders_idorders` , `Orders_Users_idUsers` , `Orders_Users_UsersType_idUsersType` , `Orders_Users_UsersType_idUsersType1`)
    REFERENCES `Tempo_Bouono`.`Orders` (`idorders` , `Users_idUsers` , `Users_UsersType_idUsersType` , `Users_UsersType_idUsersType1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetalleOrdenes_Productos1`
    FOREIGN KEY (`Productos_idProductos` , `Productos_ProductType_idProductType` , `Productos_ProductDiscounts_idProductDiscounts` , `Productos_ProductType_idProductType1`)
    REFERENCES `Tempo_Bouono`.`Productos` (`idProductos` , `ProductType_idProductType` , `ProductDiscounts_idProductDiscounts` , `ProductType_idProductType1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idDetalleOrdenes_UNIQUE` ON `Tempo_Bouono`.`OrdenItems` (`idOrdenesItems` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_DetalleOrdenes_Orders1_idx` ON `Tempo_Bouono`.`OrdenItems` (`Orders_idorders` ASC, `Orders_Users_idUsers` ASC, `Orders_Users_UsersType_idUsersType` ASC, `Orders_Users_UsersType_idUsersType1` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_DetalleOrdenes_Productos1_idx` ON `Tempo_Bouono`.`OrdenItems` (`Productos_idProductos` ASC, `Productos_ProductType_idProductType` ASC, `Productos_ProductDiscounts_idProductDiscounts` ASC, `Productos_ProductType_idProductType1` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
